### ISSUE TITLE
Flooding of "Permanently added <IP> to the list of known hosts"

### ISSUE THREAD

**Issue by ain** [brikis98/docker-osx-dev#126] opened 2015-10-26 18:47 UTC
At some stage of development, I'm getting a flood of

```
[INFO] Warning: Permanently added '192.168.99.100' (ECDSA) to the list of known hosts.
```

which also seems to have impact on performance.

Is this something we could avoid or why is this happening?

**Comment by brikis98** [comment] 2015-10-26 21:55
Isn't this a duplicate of #101?

**Closed as completed** 2015-10-26 22:11 UTC
Labels: duplicate
