### ISSUE TITLE
Incorrect DOCKER_MACHINE_STORE_PATH using docker-machine 0.5 causes prompt for password on sync

### ISSUE THREAD

**Issue by marzolfb** [brikis98/docker-osx-dev#142] opened 2015-11-13 17:32 UTC
After installing docker-osx-dev, I ran it for the first time:

```
docker-osx-dev
```

and was prompted for a password:

```
2015-11-13 08:59:43 [INFO] Testing if docker machine is running
2015-11-13 08:59:44 [INFO] Installing rsync in the Docker Host image
2015-11-13 08:59:44 [INFO] Performing initial sync of paths: /Users/wsm263/Development/bret-blog
docker@192.168.99.100's password: 
```

Recognizing this wasn't normal, I ran with the debug flag (`docker-osx-dev -l DEBUG`) and discovered the rsync command was using the wrong location for the id_rsa key.

I worked around it by changing this:

```
DOCKER_HOST_SSH_KEY="$DOCKER_MACHINE_STORE_PATH/id_rsa"
```

to this:

```
DOCKER_HOST_SSH_KEY="$DOCKER_MACHINE_STORE_PATH/machines/$DOCKER_MACHINE_NAME/id_rsa"
```

For reference:

```
docker-machine -version
```

is

```
docker-machine version 0.5.0 (04cfa58)
```

**Comment by brikis98** [comment] 2015-11-13 21:17
Looks like a duplicate of #140. Closing to keep the discussion consolidated to that bug.

**Closed as completed by brikis98** 2015-11-13 21:17 UTC
