### ISSUE TITLE
docker-osx-dev install: returns "tar: write error: No space left on device"

### ISSUE THREAD

**Issue by jefftune** [brikis98/docker-osx-dev#185] opened 2016-04-18 18:44 UTC
I download this script and gave it a try, however, I get `"tar: write error: No space left on device"`

```
docker-osx-dev install
2016-04-18 10:26:52 [INFO] Starting install of docker-osx-dev
2016-04-18 10:26:52 [INFO] Updating HomeBrew
...
2016-04-18 10:36:10 [INFO] Performing initial sync of paths: /Users/jefft
2016-04-18 10:36:10 [INFO] Initial sync using tar for /Users/jefft
tar: write error: No space left on device
exit status 1
```

However, I have more than enough space on my Yosemite OSX:

```
$ df
Filesystem    512-blocks      Used Available Capacity  iused    ifree %iused  Mounted on
/dev/disk1     487849984 130432696 356905288    27% 16368085 44613161   27%   /
```

Thanks

**Comment by brikis98** [comment] 2016-04-19 09:42
You're probably out of disk space or memory on the Docker VM, not your host OS. See:

http://stackoverflow.com/questions/30604846/docker-error-no-space-left-on-device 
http://stackoverflow.com/questions/31909979/docker-machine-no-space-left-on-device

**Comment by ain** [comment] 2016-04-19 09:54
Dupe of #169.

**Closed as completed by ain** 2016-04-19 09:54 UTC
Labels: duplicate

**Comment by ain** [comment] 2016-04-19 09:55
@jefftune some advice: do not run `docker-osx-dev` in your user folder without a good `.dockerignore` file. That will run you out in notime. Use the `.dockerignore` to limit the amount of synced files to bare minimum that delivers for your application.

**Comment by jefftune** [comment] 2016-04-21 08:04
Thx for the feedback
