### ISSUE TITLE
File syncing doesn't work

### ISSUE THREAD

**Issue by erez-rabih** [brikis98/docker-osx-dev#15] opened 2015-05-21 12:28 UTC
Hi,

I really appreciate your take to make docker and osx development a lot easier for all of us.
I tried using docker-osx-dev and everything worked well but file changes I made on local files are not reflected in the docker container...
I am wondering how can I investigate what I'm doing wrong. Are there are restrictions to how I can share folders?

This is the relevant part of my compose.yml:
rails:
    build: .
    environment:
        RAILS_ENV: development
    command: "bundle exec rails s"
    working_dir: /var/www/rails_app/
    expose:
        - "3000"
    volumes:
        - .:/var/www/rails_app/

I was expecting that changes I make on my local files will be reflected on /var/www/90min on the docker container but they are not...

Any help would be appreciated :)

**Comment by erez-rabih** [comment] 2015-05-21 12:32
And to make things clearer I SSH'd into the vagrant VM and I didn't see the changes in the files there also, meaning the rsync between my host and Vagrant has somehow broken.
Also, I have put

``` ruby
    puts "Syncing #{folder[:src]} to #{folder[:dest]}"
```

In the folders_to_sync block and I did see there my local folder

**Comment by brikis98** [comment] 2015-05-21 17:54
In what folder on your host computer are you running docker-osx-dev? In your `docker-compose.yml` file, the source directory is `.`, so I'm trying to figure out what folder that resolves to. Once you have that, could you run `vagrant ssh` and go to _the exact same folder_ to see if your files are actually being synced there?

**Comment by brikis98** [comment] 2015-05-21 18:02
Oh wait, is your file called `compose.yml` and not `docker-compose.yml`?

**Comment by erez-rabih** [comment] 2015-05-21 21:39
Hi,
After chasing this I found out that it was because I had upper case letters in the folder name on my mac host.
Changing the directory name from MyApp to myapp solved it and now the auto rsync picks my changes.
Weird isn't it?

**Comment by brikis98** [comment] 2015-05-21 21:44
That is a bit odd. The Mac file system is [case insensitive but case preserving](http://apple.stackexchange.com/a/22304). I wonder if some sort of mixup happens once you move the files to Linux which is case sensitive?

I'll close this issue for now, but I'm not 100% sure I understand the root cause yet, so I'll keep it in mind. If you figure anything else out, let me know!

**Comment by JKrag** [comment] 2015-05-29 15:04
Hi Yevgeniy. 
I think I can confirm the same problem on my local setup.
I tried to get everything running on my machine where I already had boot2docker and a million stuff installed, and never got it to run reliably. Then I saw this closed issue, and thought it would be worth a try. 
I moved my repository from /Users/jan/Documents/github/pinside to /private/tmp/test/pinside ( a random choice for a path with NO uppercase at all).
After this, the file watch seemed to work better. 

For test purposes, and because I by coincidence had a "clean" mac at hand (i.e. no docker/b2d ever), I tried to do a straight install of your tool on that (which worked fine by the way).
On this I tried to replicate the same scenario, with seemingly the same result. I.e. it didn't discover changed files when under ~/repos/<repo with uppercase name> but worked fine when i copied the directory to /private/tmp/lowercase.

By running docker-osx-dev -l DEBUG, it looks as if it is fswatch that fails to pick up the changes, and thus never calls your sync function.

I haven't really tested yet if this is actually due to the lowercase path, or if it because there is some other relevant difference between /Users/username/... and /private/tmp/... 
I will try to see if I can test this later.

(Oh, and I learned the hard way that your script handles symlinks a bit unexpectedly. I will create a new issue for that, even though it might be "expected behaviour". Then others can find it and know. )

Regards Jan

**Comment by brikis98** [comment] 2015-05-29 17:24
@JKrag: Interesting. I have mixed case in my paths (`/Users/brikis98/..`) and docker-osx-dev and fswatch seem to work fine. I wonder what the difference is?

Out of curiosity, what happens if you run the following in one of those folders:

``` sh
fswatch .
```

Leave that running in a terminal, make some changes in that folder (e.g. `touch foo`), and let me know if fswatch outputs anything to stdout.

**Comment by JKrag** [comment] 2015-05-29 21:40
When I run `fswatch .` as suggested, then everything works fine.
So I did a little digging to see if I could reproduce the failure case.

First I tested specifying the path in full (same path as current dir) `fswatch /Users/jan/repos/AaBbCc`and everything still worked fine.
(Then I tried adding -0 as you do, which my fswatch refused, even though it is mentioned in the usage printout.... but lets ignore that)
Finally I tried with the --exclude .git , and then it gets interesting, because now it _doesn't_ detect file changes any more. 
Note, I then noticed in that fswatch man page that --exclude expects a regex, and thought that the `.` wildcard might be throwing us off. 
However 
`fswatch --exclude=\.git .` 
and even 
`fswatch --exclude="\.git" .`
also make it fail to detect any file changes.

So it seems that I can "isolate" the problem and replicate the failure mode "outside" docker-osx-dev.

To test whether it was the exclude itself that made it fail, I tried:
`fswatch --exclude=AAA .`
instead.
Now it has no problem detecting `touch BBB` and still correctly ignores `echo "aaa" >> AAA`

hmmm....

**Comment by JKrag** [comment] 2015-05-29 22:16
Ahhh.... and 5 seconds later it dawned on me.

All the repos I am testing on (websites that I want to build with a Jekyll docker image) are located on my machine under `~/Documents/github/<reponame>`

It seems that fswatch must be applying its exclude regex to the full path, thus matching my /github/ path :-(
And to make things worse, when I was testing the above cases on the "clean room" mac, I made it even worse. even though I had there randomly chosen ~/repos/ as my root path, thus avoiding the problem, I had unfortunately chosen to clone a github pages repo, so this included not only github, but actually `<MyRePo>.github.io` in the actual repo name.
This of course had the consequence that even when I was "smart" and escaped the wildcard (.git) it still matched. Very confusing until you spot it :-)

Specifying the full path in the exclude (--exclude=/Users/more_path/.git ) actually solves this problem, but still ignores changes to .gitignore (which could be argued either way), and worse, also changes to a file called Agit, and this is obviously not good behaviour.

A solution to the latter problem is to quote the regex and escape the dot (`--exclude="/Users/more_path/\.git"`)

This still ignores the .gitignore file, but I can live with that. I tried avoiding this by using ´.git$´, but so far haven't made it work (e.g. it no longer matches .git folder, so `echo "A" >> .git/JAN` isn't ignored.

I actually think, that if we could get git$ to work correctly, then you could get away with not adding the full path, and just use --exclude="/.git$", but I can't make this regex match correctly right now.

But all in all, my original suspicion that there might have been something besides cases in paths at place now makes more sense. By moving my repo to /tmp/... and renaming it to a short testname without cases, I was "unfortunately" also avoiding the actual cause of the problem.

I think that is all for now. Let me know if there is anything more I can test.

Cheers Jan

**Comment by brikis98** [comment] 2015-05-30 02:18
@JKrag: Great detective work. I had no idea that `--exclude foo` would exclude any path with `foo` in it. This is definitely a problem, as it will lead to MANY invalid exclusions. Let me poke around the `fswatch` settings to see what can be done.

**Comment by brikis98** [comment] 2015-05-30 22:42
@JKrag: OK, I just looked into the behavior of `.gitignore` files and found the following: 
1. If you have `foo` in your `.gitignore` file, then git will ignore `foo` appearing _anywhere_ in the path, including `./foo`, `./abc/foo`, and `./abc/foo/bar`.  
2. However, it will only ignore full path matches on `foo`, so `./foobar` and `./abc/foobar` will _not_ be ignored.
3. On the other hand, if you specify `--exclude foo` with fswatch, it will ignore `foo` appearing _anywhere_ in the path, including `./foo`, `./foobar`, `./barfoobaz`, and so on.

I believe that (3) above violates the principle of least surprise. Unfortunately, none of the settings in fswatch seem to modify this behavior, so I think I'm going to have to not use the `--exclude` flag and find a way to filter files myself.

**Comment by JKrag** [comment] 2015-05-30 23:51
Maybe you could get away with prepending the current path to any ignores, e.g. `--exclude=[current working dir]/.git`
I think this might do the trick, but unsure whether it would surface other surprising behaviour?

**Comment by brikis98** [comment] 2015-05-31 17:58
@JKrag: Unfortunately, even `--exclude "$(pwd)/foo"` doesn't do it, as it will exclude `./foobar`. I'd probably need some sort of messy regex to make sure `foo` always appears between slashes or at the end of a path, but that doesn't seem like a good approach.

**Comment by JKrag** [comment] 2015-06-03 14:03
Hi Yevgeniy. 
I think I might have found something that works for excluding .git folder from fswatch without false positives.
We want to exclude exactly the .git folder, and anything below, but not e.g. .gitignore, and also not exclude the whole project just because some folder in the path has something like xyz.github.io in the path.
I couldn't get fswatch to understand `/\.git[$|/]` (= either full path ends in .git, or contains `/.git/` ) but if I specify two excludes, it works:

`fswatch -e "/\.git$" -e "/\.git/" .`

The even more explicit safer version is:

`fswatch -e "$(pwd)/\.git$" -e "$(pwd)/\.git/" .`

Testing with fswatch directly, it now ignores
`echo "A" >> .git/JAN`
but correctly notices:
`echo "A" >> .gitignore`
and
`echo "A" >> agit` 

Even when my repo (and thus path) is something like ~/repos/xyz.github.io/ I haven't noticed it misbehave.

I was going to make the fix and send you a PR, but I am unsure how you would prefer to support and integrate a default multi-exclude nicely with your command line exclude option and the ignore-file support.
This means that I haven't actually tested this in context of the docker-osx-dev script itself, but I have tested by manually running the fswatch command that is output by your script.

I hope this is enough to help you fix the problem.
/Jan

**Comment by brikis98** [comment] 2015-06-03 17:08
@JKrag: Good investigative work, thanks!

As an alternative option, I've been running a modified version of the `docker-osx-dev` script locally where I removed the `--exclude` options from the `fswatch` command entirely and let rsync handle it with its own `--exclude` parameters. I end up with more noise in `stdout` about file changes that are ultimately ignored... But it seems to work reasonably well and I'm tempted to check it in. Thoughts?

**Closed as completed** 2015-06-03 22:19 UTC
Labels: bug, help wanted

**Comment by brikis98** [comment] 2015-06-03 22:20
@JKrag: I just tested out the option of letting rsync handle all the excludes and it seems to work very well. I also changed the way rsync logs so that it only writes to stdout when something actually changes. Give it a shot and let me know if it works for you.

**Comment by noahsw** [comment] 2015-06-04 03:46
Working like a charm over here! And it fixed some weird rsync permission denied errors as well.
