### ISSUE TITLE
Install fails do to brew-cask

### ISSUE THREAD

**Issue by shawnmaten** [brikis98/docker-osx-dev#165] opened 2016-01-18 20:53 UTC
I tried installing after creating and setting the env for a docker machine. My installation failed as follows:

```
Shawns-MacBook-Pro:docker shawnaten$ curl -o /usr/local/bin/docker-osx-dev https://raw.githubusercontent.com/brikis98/docker-osx-dev/master/src/docker-osx-dev
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 40599  100 40599    0     0  54366      0 --:--:-- --:--:-- --:--:-- 54349
Shawns-MacBook-Pro:docker shawnaten$ chmod +x /usr/local/bin/docker-osx-dev
Shawns-MacBook-Pro:docker shawnaten$ docker-osx-dev install
2016-01-18 14:20:57 [INFO] Starting install of docker-osx-dev
2016-01-18 14:20:57 [INFO] Updating HomeBrew
Already up-to-date.
2016-01-18 14:21:02 [INFO] Installing Cask
==> Installing brew-cask from caskroom/cask
==> Cloning https://github.com/caskroom/homebrew-cask.git
Cloning into '/Library/Caches/Homebrew/brew-cask--git'...
remote: Counting objects: 3408, done.
remote: Compressing objects: 100% (3370/3370), done.
remote: Total 3408 (delta 61), reused 409 (delta 17), pack-reused 0
Receiving objects: 100% (3408/3408), 5.88 MiB | 988.00 KiB/s, done.
Resolving deltas: 100% (61/61), done.
Checking connectivity... done.
Note: checking out 'b4c92f3658d47712aa6114fb29be50a763cf78ee'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

==> Checking out tag v0.60.1
==> Caveats
You must uninstall this formula. It is no longer needed to stay up to date,
as Homebrew now takes care of that automatically.
==> Summary
🍺  /usr/local/Cellar/brew-cask/0.60.1: 4 files, 7.6K, built in 10 seconds
2016-01-18 14:21:14 [ERROR] Failed to install dependency Cask. Check the log output above for reasons.
```

**Comment by brikis98** [comment] 2016-01-18 22:55
Closing, as this is a duplicate of #162.

**Closed as completed by brikis98** 2016-01-18 22:55 UTC
