### ISSUE TITLE
Nodemon restarts multiple times for a single file change

### ISSUE THREAD

**Issue by noahsw** [brikis98/docker-osx-dev#11] opened 2015-05-20 05:13 UTC
This does not repro using the standard boot2docker config.

Repro:
1. Running containers via `docker-compose`. Local `src` folder is mounted into `webapp` container.
2. Nodemon is run via `NODE_ENV=development nodemon ./bin/www`
3. Change a file monitored by Nodemon. I tried both Sublime 2 and RubyMine and had the same result.

Results:

```
webapp_1 | 20 May 05:09:22 - [nodemon] restarting due to changes...
webapp_1 | 20 May 05:09:22 - [nodemon] starting `node ./bin/www`
webapp_1 | 20 May 05:09:23 - [nodemon] restarting due to changes...
webapp_1 | 20 May 05:09:23 - [nodemon] starting `node ./bin/www`
webapp_1 | 20 May 05:09:24 - [nodemon] restarting due to changes...
webapp_1 | 20 May 05:09:24 - [nodemon] starting `node ./bin/www`
webapp_1 | 20 May 05:09:25 - [nodemon] restarting due to changes...
webapp_1 | 20 May 05:09:25 - [nodemon] starting `node ./bin/www`
webapp_1 | 20 May 05:09:26 - [nodemon] restarting due to changes...
webapp_1 | 20 May 05:09:26 - [nodemon] starting `node ./bin/www`
webapp_1 | 20 May 05:09:27 - [nodemon] restarting due to changes...
webapp_1 | 20 May 05:09:27 - [nodemon] starting `node ./bin/www`
webapp_1 | 20 May 05:09:28 - [nodemon] restarting due to changes...
webapp_1 | 20 May 05:09:28 - [nodemon] starting `node ./bin/www`
```

Notice the timestamps. It's restarting multiple times for a single change.

**Comment by brikis98** [comment] 2015-05-20 19:13
Good catch. 

Repro steps:

Dockerfile:

``` docker
FROM gliderlabs/alpine:3.1

RUN apk-install nodejs
RUN npm install -g nodemon

RUN mkdir -p /src
VOLUME /src
WORKDIR /src
ADD . /src

EXPOSE 1337
CMD ["nodemon", "server.js"]
```

Commands:

```
> docker build -t node-test .
> docker run --rm -v $(pwd):/src -p 1337:1337 node-test
```

Output after making a single change to `server.js` on OS X:

```
Server running at http://0.0.0.0:1337/
20 May 19:10:08 - [nodemon] restarting due to changes...
20 May 19:10:08 - [nodemon] starting `node server.js`
Server running at http://0.0.0.0:1337/
20 May 19:10:08 - [nodemon] restarting due to changes...
20 May 19:10:08 - [nodemon] starting `node server.js`
Server running at http://0.0.0.0:1337/
```

I'm not sure what the cause is yet, but I'll poke around.

**Comment by brikis98** [comment] 2015-05-20 19:24
Further investigation: this is _not_ caused by the [vagrant-gatling-rsync](https://github.com/smerrill/vagrant-gatling-rsync) plugin. If I stop automatic syncing and just manually sync a single file change using `vagrant rsync`, it still causes nodemon to restart twice. Looking further...

**Comment by brikis98** [comment] 2015-05-20 19:43
OK, by enabling verbose logging in nodemon with the `-V` flag, it turns out there are a few things happening here:

```
20 May 19:29:12 - [nodemon] files triggering change check: .server.js.8ajJIp
20 May 19:29:12 - [nodemon] changes after filters (before/after): 1/0
20 May 19:29:12 - [nodemon] files triggering change check: .server.js.8ajJIp
20 May 19:29:12 - [nodemon] changes after filters (before/after): 1/0
20 May 19:29:12 - [nodemon] files triggering change check: .server.js.8ajJIp
20 May 19:29:12 - [nodemon] changes after filters (before/after): 1/0
20 May 19:29:12 - [nodemon] files triggering change check: .server.js.8ajJIp
20 May 19:29:12 - [nodemon] changes after filters (before/after): 1/0
20 May 19:29:12 - [nodemon] files triggering change check: .server.js.8ajJIp
20 May 19:29:12 - [nodemon] changes after filters (before/after): 1/0
20 May 19:29:12 - [nodemon] files triggering change check: .server.js.8ajJIp
20 May 19:29:12 - [nodemon] changes after filters (before/after): 1/0
20 May 19:29:12 - [nodemon] files triggering change check: server.js
20 May 19:29:12 - [nodemon] matched rule: **/*.*
20 May 19:29:12 - [nodemon] changes after filters (before/after): 1/1
20 May 19:29:12 - [nodemon] restarting due to changes...
20 May 19:29:12 - [nodemon] server.js

20 May 19:29:12 - [nodemon] files triggering change check: src
20 May 19:29:12 - [nodemon] changes after filters (before/after): 1/0
20 May 19:29:12 - [nodemon] starting `node server.js`
20 May 19:29:12 - [nodemon] child pid: 75
20 May 19:29:12 - [nodemon] watching 3 files
Server running at http://0.0.0.0:1337/
20 May 19:29:12 - [nodemon] files triggering change check: server.js
20 May 19:29:12 - [nodemon] matched rule: **/*.*
20 May 19:29:12 - [nodemon] changes after filters (before/after): 1/1
20 May 19:29:12 - [nodemon] restarting due to changes...
20 May 19:29:12 - [nodemon] server.js

20 May 19:29:12 - [nodemon] starting `node server.js`
20 May 19:29:12 - [nodemon] child pid: 83
20 May 19:29:12 - [nodemon] watching 3 files
Server running at http://0.0.0.0:1337/
```

So three things are triggering a restart:
1. A change to `server.js`. This the only change we care about.
2. A change to `.server.js.8ajJIp`. Is this some temporary file used by sublime or vim?
3. A change to the `src` folder. Perhaps rsync is updating the timestamps on this folder?

The easiest solution for now is probably to increase the [nodemon delay](https://github.com/remy/nodemon#delaying-restarting) flag so it doesn't restart immediately after every change, but waits a little while for a batch of them. In the meantime, I'll see if there are some rsync flags that will fix issues 2 and 3.

**Comment by brikis98** [comment] 2015-05-20 20:30
OK, I just added several rsync settings to the `Vagrantfile` that may improve things:
1. `--omit-dir-times`: don't update timestamps on folders. This way, the root folder of the project doesn't get updated for every single file change that happens within it.
2. `--inplace`: by default, rsync creates a temporary file and then merges it into the original file. The `inplace` flag tells it to skip the temporary file thing and replace the original file.
3. `--whole-file`: replace the entire file at once instead of applying diffs. 

Now when I make a single change, I see the following:

```
20 May 20:25:00 - [nodemon] restarting due to changes...
20 May 20:25:00 - [nodemon] restarting due to changes...
20 May 20:25:00 - [nodemon] restarting due to changes...
20 May 20:25:00 - [nodemon] starting `node server.js`
Server running at http://0.0.0.0:1337/
```

So nodemon is still detecting multiple changes, but only actually restarting once, which is an improvement. With verbose logging, it looks like it's detecting multiple changes to the same file (`server.js`), so perhaps rsync is still updating it in stages, despite the `--whole-file` flag. Not sure what I can do about that, but as long as you only get one restart, it shouldn't matter, right?

To try out the new version, run:

```
> docker-osx-dev stop
> vagrant destroy
> rm -f Vagrantfile
> docker-osx-dev init
> docker-osx-dev start
```

**Comment by brikis98** [comment] 2015-05-21 17:52
Based on the latest updates, I'm closing this issue. Please re-open if you're still having problems.

**Closed as completed by brikis98** 2015-05-21 17:52 UTC
