### ISSUE TITLE
setup.sh stops after rsync install into boot2docker

### ISSUE THREAD

**Issue by ilkka** [brikis98/docker-osx-dev#26] opened 2015-05-26 12:22 UTC
As of today, setup.sh for me does this:

```
curl https://raw.githubusercontent.com/brikis98/docker-osx-dev/master/setup.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13690  100 13690    0     0   6491      0  0:00:02  0:00:02 --:--:--  6491
[INFO] Updating HomeBrew
Updated Homebrew from e9ae5916 to 03e4c2a5.
==> Updated Formulae
stty: stdin isn't a terminal
monit
[WARN] Cask is already installed by HomeBrew, skipping
[WARN] Found command VBoxManage, assuming VirtualBox is already installed and skipping
[WARN] Boot2Docker is already installed by HomeBrew, skipping
[WARN] Found command docker-compose, assuming Docker Compose is already installed and skipping
[WARN] fswatch is already installed by HomeBrew, skipping
[WARN] GNU core utilities is already installed by HomeBrew, skipping
[INFO] Initializing Boot2Docker VM
Latest release for github.com/boot2docker/boot2docker is v1.6.2
Downloading boot2docker ISO image...
Success: downloaded https://github.com/boot2docker/boot2docker/releases/download/v1.6.2/boot2docker.iso
    to /Users/ilau/.boot2docker/boot2docker.iso
Generating public/private rsa key pair.
Your identification has been saved in /Users/ilau/.ssh/id_boot2docker.
Your public key has been saved in /Users/ilau/.ssh/id_boot2docker.pub.
The key fingerprint is:
48:48:00:ce:f1:e6:61:e1:6c:cf:f9:1c:f7:e8:2b:fe ilau@dyn-100-137.wlan.futurice.org
The key's randomart image is:
+--[ RSA 2048]----+
|.o.o.            |
|o =...           |
| o O. .          |
|  = +...         |
|   . +..S.       |
|      o o o      |
|       o . .     |
|       ..        |
|      ..oE.      |
+-----------------+
[INFO] Starting Boot2Docker VM
Waiting for VM and Docker daemon to start...
.........................ooooooooooooooooooooooo
Started.
Writing /Users/ilau/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/ilau/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/ilau/.boot2docker/certs/boot2docker-vm/key.pem
Your environment variables are already set correctly.

[INFO] Installing rsync in the Boot2Docker image
Downloading: popt.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
popt.tcz              12% |****                           |  3724   0:00:06 ETApopt.tcz: OK
popt.tcz             100% |*******************************| 28672   0:00:00 ETA
Downloading: rsync.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
rsync.tcz             19% |*****                          | 35115   0:00:04 ETArsync.tcz: OK
rsync.tcz            100% |*******************************|   180k  0:00:00 ETA
$ echo $?
0
```

However, at this point ssh'ing into boot2docker reveals

```
docker@boot2docker:~$ which rsync
/usr/local/bin/rsync
```

so apparently the install succeeded. Also, running setup.sh a second time _usually_ goes through to the very end, although just now I had an incident where it just quit immediately after checking if rsync is already installed.

**Comment by brikis98** [comment] 2015-05-26 18:06
Hm, I fixed [a bug yesterday](https://github.com/brikis98/docker-osx-dev/commit/c8a7353e082d2326cb9df826c1ec3fc032f05151) where `setup.sh` was exiting right after the rsync install. I'm unable to repro now, both with a fresh Boot2Docker image and with an image that already has rsync installed. Is it possible you ran the code just before my fix?

**Comment by pschneider** [comment] 2015-05-26 20:54
I had the same problem. Fixed it by deleting /usr/local/bin/docker-osx-dev because the new version didn't get installed by running the setup again and there was still stuff about the Vagrantfile included.

Running the setup again installed the new version of the script. Only problem was that fswatch was installed but not linked because of the following problem:

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink share/man/man7/fswatch.7
/usr/local/share/man/man7 is not writable.
```

Running the following script https://gist.github.com/rpavlik/768518 and then linking fswatch again worked.

Also a strange thing I noticed:

```
~/Sites
» curl https://raw.githubusercontent.com/brikis98/docker-osx-dev/master/setup.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13703  100 13703    0     0  61403      0 --:--:-- --:--:-- --:--:-- 61448
[INFO] Updating HomeBrew
Already up-to-date.
[WARN] Cask is already installed by HomeBrew, skipping
[WARN] Found command VBoxManage, assuming VirtualBox is already installed and skipping
[WARN] Boot2Docker is already installed by HomeBrew, skipping
[WARN] Docker Compose is already installed by HomeBrew, skipping
[WARN] fswatch is already installed by HomeBrew, skipping
[WARN] GNU core utilities is already installed by HomeBrew, skipping
[INFO] Installing rsync in the Boot2Docker image
------------------------------------------------------------
~/Sites
» curl https://raw.githubusercontent.com/brikis98/docker-osx-dev/master/setup.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13703  100 13703    0     0  36085      0 --:--:-- --:--:-- --:--:-- 36155
[INFO] Updating HomeBrew
Already up-to-date.
[WARN] Cask is already installed by HomeBrew, skipping
[WARN] Found command VBoxManage, assuming VirtualBox is already installed and skipping
[WARN] Boot2Docker is already installed by HomeBrew, skipping
[WARN] Docker Compose is already installed by HomeBrew, skipping
[WARN] fswatch is already installed by HomeBrew, skipping
[WARN] GNU core utilities is already installed by HomeBrew, skipping
[INFO] Installing rsync in the Boot2Docker image
[INFO] Adding /usr/local/bin/docker-osx-dev
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15257  100 15257    0     0  53445      0 --:--:-- --:--:-- --:--:-- 53533
[WARN] /etc/hosts already contains dockerhost, will not overwrite
[INFO] Adding DOCKER_HOST to /Users/patrick/.zshrc
[INFO] Adding DOCKER_CERT_PATH to /Users/patrick/.zshrc
[INFO] Adding DOCKER_TLS_VERIFY to /Users/patrick/.zshrc
[INSTRUCTIONS] New environment variables defined. To pick them up in the current shell, run:
    source /Users/patrick/.zshrc
[INFO] docker-osx-dev setup has completed successfully.
[INSTRUCTIONS] You can now start file syncing using the docker-osx-dev script and run Docker containers using docker run. Example:
     > docker-osx-dev
     > docker run -v $(pwd):/src some-docker-container
```

Why did it run further after executing the setup a second time? Maybe that is your problem, too @ilkka

**Comment by brikis98** [comment] 2015-05-26 21:23
@pschneider: The `setup.sh` script also stopped for you after the "Installing rsync" part? 

Also, I'm not clear on what caused the permissions issue with fswatch. Is it some issue in HomeBrew?

**Comment by pschneider** [comment] 2015-05-27 21:38
Yes, but it seems really random.

My boot2docker vm was turned off and I ran the script again and it stopped on the following output:

```
[INFO] Installing rsync in the Boot2Docker image
Downloading: popt.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
popt.tcz: OK
popt.tcz             100% |*******************************| 28672   0:00:00 ETA
Downloading: rsync.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
rsync.tcz             46% |**************                 | 85231   0:00:01 ETArsync.tcz: OK
rsync.tcz            100% |*******************************|   180k  0:00:00 ETA
```

Then running the setup.sh again everything worked:

```
[INFO] Installing rsync in the Boot2Docker image
[INFO] Adding /usr/local/bin/docker-osx-dev
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15257  100 15257    0     0  52784      0 --:--:-- --:--:-- --:--:-- 52792
[WARN] /etc/hosts already contains dockerhost, will not overwrite
[WARN] Your shell (/bin/zsh) already defines DOCKER_HOST (e.g. perhaps in /Users/patrick/.zshrc), will not overwrite
[WARN] Your shell (/bin/zsh) already defines DOCKER_CERT_PATH (e.g. perhaps in /Users/patrick/.zshrc), will not overwrite
[WARN] Your shell (/bin/zsh) already defines DOCKER_TLS_VERIFY (e.g. perhaps in /Users/patrick/.zshrc), will not overwrite
[INFO] docker-osx-dev setup has completed successfully.
[INSTRUCTIONS] You can now start file syncing using the docker-osx-dev script and run Docker containers using docker run. Example:
     > docker-osx-dev
     > docker run -v $(pwd):/src some-docker-container
```

Maybe the script was blocked because the vm wasn't fully loaded and the boot2docker ip command failed?

Now running the setup.sh again it crashes randomly on

```
....
[INFO] Installing rsync in the Boot2Docker image
```

And sometimes it works as intended

```
....
[INFO] Installing rsync in the Boot2Docker image
[INFO] Adding /usr/local/bin/docker-osx-dev
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15257  100 15257    0     0  81888      0 --:--:-- --:--:-- --:--:-- 82026
[WARN] /etc/hosts already contains dockerhost, will not overwrite
....
```

Running the install_rsync_on_boot2docker check manually always works.
Also it works every time when I run the setup.sh script locally. So it's quite hard to figure out why it fails sometimes when downloading via curl from Github.

Regarding the Homebrew issue I think this could've been related to my system because I upgraded this every time since 10.5 so maybe something broke on the way. I do not install new formulas very often.

**Comment by brikis98** [comment] 2015-05-28 00:13
Ah, I didn't realize it only failed when run via `curl`. I'm able to repro it now as well: the script intermittently  stops or hangs at the "Installing rsync" part. Very weird. I'm not sure what could cause this. The code is pretty simple:

``` sh
boot2docker ssh "if ! type rsync > /dev/null 2>&1; then tce-load -wi rsync; fi"
```

Is there some crazy interaction between reading the `setup.sh` script from `stdin` and using `boot2docker ssh`??

**Comment by brikis98** [comment] 2015-05-28 00:22
I just made the commit above to change the instructions in the README to say:

``` sh
bash <(curl -s https://raw.githubusercontent.com/brikis98/docker-osx-dev/master/setup.sh)
```

That seems to be the recommended approach in this [StackOverflow thread](http://stackoverflow.com/questions/5735666/execute-bash-script-from-url) and in my local testing, it seems to work correctly every time. Could you try it out and see if it works better for you?

**Comment by pschneider** [comment] 2015-05-28 22:24
Seems fine now :+1:

**Comment by brikis98** [comment] 2015-05-28 22:25
Awesome, thanks. Closing the issue now.

**Closed as completed by brikis98** 2015-05-28 22:25 UTC
